tasks:
  - init: go get 

github:
    prebuilds:
        pullRequestsFromForks: true

ports:
  - port: 8080
    onOpen: open-preview
  - port: 26257
    onOpen: open-preview

vscode:
  extensions:
    - golang.go
    - DavidAnson.vscode-markdownlint
    - mdickin.markdown-shortcuts
    - timonwong.shellcheck
    - premparihar.gotestexplorer